---
openapi: 3.0.1
info:
  title: API V1
  version: v1
  description: URL shortening service
servers:
- url: http://localhost:3000
  variables:
    endPoint:
      default: http://localhost:3000
  description: localhost
- url: https://staging.mandyseeyoo.com
  variables:
    endPoint:
      default: https://staging.mandyseeyoo.com
  description: staging
